# Local environment variables.
[[ -f ~/.zshenv.local ]] && source ~/.zshenv.local

export DOTFILES=$HOME/.dotfiles

export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share

# Load everything else.
for DOTFILE in $DOTFILES/zsh/env/*(.)
do
	[[ -f "$DOTFILE" ]] && source "$DOTFILE"
done
