export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share

export ZDOTDIR=$XDG_CONFIG_HOME/zsh

export EDITOR=/usr/bin/nvim
export PAGER=/usr/bin/less

export RUSTUP_HOME=$XDG_DATA_HOME/rustup
export CARGO_HOME=$XDG_DATA_HOME/cargo

PATH="$HOME/.cargo/bin:$PATH"
PATH="$HOME/.local/cross/:$PATH"
source "/home/noah/.local/share/cargo/env"
