export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share

export ZDOTDIR=$XDG_CONFIG_HOME/zsh

export EDITOR=/bin/nvim
export PAGER=/bin/less

PATH="$HOME/.local/bin:$PATH"
PATH="$HOME/.local/cross/bin:$PATH"
PATH="$HOME/.cargo/bin:$PATH"
