# Local configuration.
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local

export DOTFILES=$HOME/.dotfiles
# Load everything else.
for DOTFILE in $DOTFILES/zsh/rc/*(.)
do
	[[ -f "$DOTFILE" ]] && source "$DOTFILE"
done

bindkey -v

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
